### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(BottomLayer)
add_subdirectory(Digital_Cluster_DesignStudio)
add_subdirectory(Digital_Cluster_DesignStudioContent)
add_subdirectory(Gauge)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    BottomLayerplugin
    Digital_Cluster_DesignStudioplugin
    Digital_Cluster_DesignStudioContentplugin
    Digital_Cluster_DesignStudioContent_Content_Areaplugin
    Gaugeplugin
    QtQuickDesignerComponents)