# control interface for wpi_cli tool 
# useful for debugging 
ctrl_interface=/var/run/wpa_supplicant
# allow wpa_cli to update this file through root group
ctrl_interface_group=0
# let wpa_supplicant to update this file at runtime
update_config=1
# my wifi network is Ro
network={
    ssid="Ro"
    psk="87654321"

    key_mgmt=WPA-PSK
}
