// Ported from 02-Digital-Cluster/Gauge/GaugeLabels.qml — pure Text elements
// positioned by polar math, no Canvas, no per-label rotation. Per PLAN.md's
// audit this was already compliant before the rebuild started, so it's ported
// close to verbatim; the only change is the Theme import (C++ QML_SINGLETON
// now, so it needs an explicit `import QnxCluster`).
//
// S5 COST TO WATCH: each label carries a `Behavior on color` ColorAnimation,
// so the `animations=` bucket in the Frame prepared line grows with the label
// count. At S5 that is 9 labels per gauge (speed 0..240 step 30, rpm 0..8
// step 1) = 18 total, which should be negligible — but S6 adds tick marks,
// and the original ran ~98 concurrent ColorAnimations across both gauges.
// This component is where that growth starts, so note the `animations=`
// number now to have a baseline to compare S6 against.
//
// Note the labels' angle convention MUST stay in sync with GaugeActiveArc
// (startAngle 135, sweepAngle 270) and, later, GaugeTickMarks — a mismatch
// shows up as labels drifting off their ticks rather than as an error.

import QtQuick
import QnxCluster

Item {
    id: labelsRoot

    // ════════════════════════════════════════════════════
    //  PUBLIC API
    // ════════════════════════════════════════════════════

    // Driving value
    property real value:    0
    property real maxValue: 240

    // Step between labels (should match GaugeTickMarks.bigStep)
    property real labelStep: 30

    // Where labels sit (distance from center)
    property real labelRadius: 160

    // Angle range — MUST match GaugeActiveArc and GaugeTickMarks
    property real startAngle: 135   // 0 value sits here
    property real sweepAngle: 270   // full sweep span

    // Typography
    property string fontFamily: Theme.fontPrimary
    property int    fontSize:   18
    property int    fontWeight: Theme.fontWeightMedium

    // Colors
    property color colorActive:  Theme.colorTextPrimary
    property color colorPassive: Theme.colorTextMuted

    // S7: switches off the per-label colour fade.
    //
    // This was added to test a hypothesis that turned out to be WRONG, and the
    // note is kept so nobody re-runs the experiment. The theory was that each
    // animating label holds its own interpolated colour, making 18 distinct
    // materials that Qt cannot merge. Measured on target: disabling it moved
    // the batch count from 23 to 22 and render by 1 ms. Colour variation is
    // not what prevents `Text` from merging.
    //
    // What IS true (measured): `Text` is the only element type in this UI that
    // does not batch — ~1 batch per 2.7 items, at ~0.5 ms per batch — while 12
    // tick `Shape` nodes and 6 redline nodes add ZERO batches and 60 segment
    // `Rectangle`s add 2-3. The fix is therefore fewer Text ITEMS, not fewer
    // Text colours: see the baked dial labels in tools/gen_bazel_frame.py.
    property bool animateColor: true


    // ════════════════════════════════════════════════════
    //  INTERNAL — generate the label model
    // ════════════════════════════════════════════════════
    readonly property var labelModel: {
        var arr = []
        for (var v = 0; v <= maxValue; v += labelStep) {
            arr.push(v)
        }
        return arr
    }

    readonly property real centerX: width  / 2
    readonly property real centerY: height / 2


    // ════════════════════════════════════════════════════
    //  LABEL RENDERING
    // ════════════════════════════════════════════════════
    //   angle = startAngle + (val / maxValue) * sweepAngle
    //   x = centerX + cos(angle) * labelRadius - width/2
    //   y = centerY + sin(angle) * labelRadius - height/2
    // ── BAKED MODE (default) ─────────────────────────────
    // 18 live Text items cost ~8 batches / ~4 ms of a 14 ms frame, purely
    // because Text is the one element type Qt does not merge (measured: ticks
    // and redline Shapes add ZERO batches, 60 segment Rectangles add 2-3).
    // The strings never change, so Rule 2 applies: bake offline, draw one
    // Image. Generated by tools/gen_dial_labels.py in this component's own
    // 450x450 coordinate space, so it inherits exactly the transform the live
    // labels did and no geometry has to be re-derived here.
    //
    // The trade is that a baked label cannot change colour, so the
    // active/passive dimming is lost — see LABEL_COLOR in the generator.
    // `--live-labels` restores the Repeater for comparison.
    property bool baked: true
    property url bakedSource: ""

    Image {
        anchors.fill: parent
        visible: labelsRoot.baked && labelsRoot.bakedSource != ""
        source: labelsRoot.bakedSource
        sourceSize: Qt.size(width, height)   // standing rule: always set this
        smooth: true
        // mipmap deliberately OFF: it excludes an image from Qt's shared
        // texture atlas and costs it a dedicated batch (~0.5 ms here). With
        // sourceSize capping the decode at display size there is no
        // minification left for mip levels to help with anyway.
        // See qml/ContentArea/TopBarButton.qml for the measurement.
        mipmap: false
    }

    Repeater {
        model: labelsRoot.baked ? [] : labelsRoot.labelModel

        delegate: Text {
            required property var modelData

            // The value this label represents
            property real labelValue: modelData

            property real angleDeg:
                labelsRoot.startAngle
                + (labelValue / labelsRoot.maxValue) * labelsRoot.sweepAngle

            property real angleRad: angleDeg * Math.PI / 180.0

            x: labelsRoot.centerX + Math.cos(angleRad) * labelsRoot.labelRadius - width / 2
            y: labelsRoot.centerY + Math.sin(angleRad) * labelsRoot.labelRadius - height / 2

            // Integer for a 0-240 speed scale, one decimal for a 0-8 rpm
            // scale — the original relied on `text: labelValue` coercing an
            // int model, which breaks once labelStep is fractional (RPM uses
            // step 1.0 with maxValue 8, and a float step elsewhere would
            // print "1.5000000000000002"). Formatting explicitly keeps both
            // call sites honest.
            text: Number.isInteger(labelValue) ? labelValue.toString()
                                               : labelValue.toFixed(1)

            color: labelValue <= labelsRoot.value
                   ? labelsRoot.colorActive
                   : labelsRoot.colorPassive

            Behavior on color {
                enabled: labelsRoot.animateColor
                ColorAnimation { duration: Theme.durationFast }
            }

            font.family:    labelsRoot.fontFamily
            font.pixelSize: labelsRoot.fontSize
            font.weight:    labelsRoot.fontWeight

            horizontalAlignment: Text.AlignHCenter
            verticalAlignment:   Text.AlignVCenter
        }
    }
}
