# Select systemd before loading poky defaults
INIT_MANAGER = "systemd"

require conf/distro/poky.conf
DISTRO = "ivi-distro"
DISTRO_NAME = "ivi-distro (IVI Reference Distro)"
DISTRO_VERSION = "1.0"
TARGET_VENDOR = "-rpi3b"
# We target Qt EGLFS, not X11/Wayland
DISTRO_FEATURES:remove = "x11 wayland sysvinit vulkan"
DISTRO_FEATURES:append = " systemd usrmerge wifi opengl dbus alsa"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
DISTRO_FEATURES_BACKFILL_CONSIDERED += " sysvinit"